### ISSUE TITLE
Token: No response

### ISSUE THREAD

**Issue by Tesla-Birne** [dbweb-ch/ioBroker.tesla-motors#97] opened 2021-08-05 12:46 UTC
After updating ioBroker to newest version Tesla Adapter does not let me get Token. Error Message "Could not retrieve token, Error from Tesla: No response"

Yesterday all was fine.

**Comment by Walkinlarge2010** [comment] 2021-08-07 20:22
i have the same problem. also an downgrade doesnt work :( i tried it 20 time. How can we fix this?

**Comment by adultano** [comment] 2021-08-08 13:11
Same issue here - did they change their API? -> no response for me too

**Comment by and-web** [comment] 2021-08-09 21:50
Duplicate of #78

Please look into issue #78, in short: Tesla is playing around with its authentication rules and that causes these disturbances. Unfortunately, the problem relates to TeslaJS and can't be solved by the maintainer of this iobroker adapter. On the other hand, the problem affects a lot more users outside of iobroker, so we can hope to have a solution brought be Tesla anyday soon...

**Comment by adultano** [comment] 2021-08-10 10:31
> Duplicate of #78
> 
> Please look into issue #78, in short: Tesla is playing around with its authentication rules and that causes these disturbances. Unfortunately, the problem relates to TeslaJS and can't be solved by the maintainer of this iobroker adapter. On the other hand, the problem affects a lot more users outside of iobroker, so we can hope to have a solution brought be Tesla anyday soon...

i can manually generate a token and refresh token with a 3rd party app. Is there no way to use these valid tokens in the iobroker adapter? The token fields are greyed out, so i cannot manually add them...

**Comment by adultano** [comment] 2021-08-13 09:04
> Duplicate of #78
> 
> Please look into issue #78, in short: Tesla is playing around with its authentication rules and that causes these disturbances. Unfortunately, the problem relates to TeslaJS and can't be solved by the maintainer of this iobroker adapter. On the other hand, the problem affects a lot more users outside of iobroker, so we can hope to have a solution brought be Tesla anyday soon...

hi - just following up here. I really think this could be solved by enabling the user to provide his own tokens. In the adpater login screen I manually enabled the token fields by changing the code from readonly to write and enabled the save and close button. I then pasted my tokens and saved it. Now it is working again. Any work is appreciated. Thanks!

**Comment by Walkinlarge2010** [comment] 2021-08-14 19:50
> > Duplicate of #78
> > Please look into issue #78, in short: Tesla is playing around with its authentication rules and that causes these disturbances. Unfortunately, the problem relates to TeslaJS and can't be solved by the maintainer of this iobroker adapter. On the other hand, the problem affects a lot more users outside of iobroker, so we can hope to have a solution brought be Tesla anyday soon...
> 
> hi - just following up here. I really think this could be solved by enabling the user to provide his own tokens. In the adpater login screen I manually enabled the token fields by changing the code from readonly to write and enabled the save and close button. I then pasted my tokens and saved it. Now it is working again. Any work is appreciated. Thanks!

Hi adultano,

is it possible to share the adjustments or share an short how to? I have no idea how I can change the settings to set the token manual. Thanks a lot!

**Comment by adultano** [comment] 2021-08-14 22:18
Hi. Yes ill post a how to guide on Monday or Tuesday. Unfortunately i am in kind of an emergeny these days but i will come back early next week.

**Comment by and-web** [comment] 2021-08-15 19:29
Looking forward to your reply on how to manipulate the json for a manually obtained token. However, please use #78 instead of this thread since it is a duplicate of an existing topic which has a bunch of people following the thread which may be interested also. Thank you. :-)

**Comment by dbweb-ch** [comment] 2021-08-16 05:42
https://github.com/dbweb-ch/ioBroker.tesla-motors/issues/78#issuecomment-899238353

**Closed** 2021-08-16 05:42 UTC
