### ISSUE TITLE
token validity as Object

### ISSUE THREAD

**Issue by lobomau76** [dbweb-ch/ioBroker.tesla-motors#29] opened 2020-11-05 11:52 UTC
Hi, 
is it possible to have the validity date of the token also as an Object?
Today was my first time that the token got invalid. I only realized it hours later. As Object I could send me reminders before it gets invalid.

It`s more a pull request, but I had a problem writing a pull request... something about choosing the right branch I guess.

**Comment by and-web** [comment] 2021-08-16 06:07
I would appreciate that also because I currently work-around this by an iobroker cron job that evaluates the last update and notifies when the last update took place more than 24 hours ago. Needless to say, sometimes the notification comes too late...

**Comment by dbweb-ch** [comment] 2021-08-16 06:39
added in master, feel free to test it. Object: info.tokenExpire

**Comment by and-web** [comment] 2021-09-15 22:18
Tested, works as designed!

I've created a script that compares the current date with the "info.tokenExpire" and notifies when the expiration date is coming closer than 5 days. That way, I have enough time to refresh the token manually.

IMHO, this issue can be marked as solved. Thank you very much!

**Closed** 2021-12-07 08:37 UTC
